### ISSUE TITLE
提示clone

### ISSUE THREAD

**Issue by rayc345** [banxian/EDUReviver#10]
我用的是正版的jlink base compact v11
尝试允许blink，显示灯刚开始确实能闪烁，大概闪烁15次后程序突然提示clone
Firmware Version: J-Link V11 compiled Nov 14 2022 17:38:39, Hardware Version: 110000
sn: 821009099, checksum OK.
UID signature mismatched!
Detected clone.

能麻烦开发者看下原因吗？谢谢，具体程序的逻辑看不太懂，还在研究。

**Comment by banxian** [comment]
037版已知问题吧, 当时增加正版v12检测合并错了代码, 会在v11设备上检测是否是v12, 在v12检测是否是v11.
等到发现时候, 已经没空改了 (我有强迫症每次发版本之前的固件适配太多手动, 所以后面干脆在重做适配逻辑, 用unicorn模拟跑固件挖了个大坑)

**Comment by rayc345** [comment]
好的，谢谢这个思路。我自己也从事软件开发，花一点时间应该可以自己改过来。

**Comment by rayc345** [comment]
关于jlink v12和v11，有点不太明白，是segger做计划性报废吗？因为两个的硬件完全是一样的，厂家出了v12，很明显对于v11的固件维护就很拉跨。还是厂家考虑v11容易克隆，通过出v12希望用户主动放弃v11

**Comment by banxian** [comment]
它有旧型号加钱换新业务. v10到v11就微调了布线的, 原理图一样, 而v11到v12(compact plus)布线甚至丝印也一样.
segger说要升级bootloader可能造成产品损坏, 因此不会给用户做自行升级, 其实我感觉还是从盈利而不是严谨方面的说法.
毕竟你需要环保不想报废可以花钱嘛, 碳税和碳排放交易不也是这样赎罪券逻辑么.
我倒是可以做免拆更新bootloader的功能, 但这玩意吃力不讨好可能还会吃官司

**Comment by rayc345** [comment]
感谢您的回复，我也是这么理解的，
刚才折腾了段时间，手上的v11 plus和v11 base成功升级到v12了。虽然有些程序细节没有理解透彻，毕竟不是做安全和逆向的。
程序里一些细节的地方，方便发私信学习一下吗？

**Comment by rayc345** [comment]
如果特别依赖jlink的生态，可以考虑jlink ob，推荐瑞萨RA4M2版本的.
有大佬基于国产RISC-V单片机做出了80M速度的SWD，如果加上RTT和Scope功能，基本就能当jlink用了，后面想试试看，添加下相关的支持。还是得靠cmsis-dap，这个最靠谱，从供应链安全、多平台适配等各个角度看。

**Comment by banxian** [comment]
暂时弃坑unicorn方案, 用直接从栈里面读取的方式来做兼容.
