### ISSUE TITLE
How to run payload on device

### ISSUE THREAD

**Issue by daniel131** [banxian/EDUReviver#2]
Hello! I have a question I compiled payload revive1.c in keil5 and I got revive1.hex file
How can i run it in my j-link 11 edu?
maybe is there the way like this: EDUReViver -run revive1.hex ?

**Comment by banxian** [comment]
first you need convert output files to binary, and try to change codes in main.cpp to load local payload instead from online service. the online service is a genuine checker and just reply patched payload with right sn checksum.
