### ISSUE TITLE
EDUReViver 运行错误

### ISSUE THREAD

**Issue by liuweiliang2006** [banxian/EDUReviver#3]
在解压缩文件夹内，打开CMD窗口，运行EDUReViver -run blinky，提示'EDUReViver' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by banxian** [comment]
可能没有进入最内层目录
也可能是EDUReViver.exe被当作恶意软件干掉了

**Comment by Claeno** [comment]
EDUReViver.exe，在工程里面吗，我也是遇到同样的问题。

**Comment by banxian** [comment]
[EDUReviver_b032_wdk.zip](https://github.com/banxian/EDUReviver/releases/download/v0.3.2-beta/EDUReviver_b032_wdk.zip)
发布页的这个是用户运行用的, 下面的源码(工程)不带exe文件
