### ISSUE TITLE
SEGGER - J-Link V7.84a驱动JLINK EDU V10无法升级到V12

### ISSUE THREAD

**Issue by neomissing** [banxian/EDUReviver#4]
SEGGER - J-Link V7.84a驱动JLINK EDU V10无法升级到V12

**Comment by banxian** [comment]
设备的v10固件是多少的? 2022 09 22的固件支持的呀

**Comment by neomissing** [comment]
> 设备的v10固件是多少的? 2022 09 22的固件支持的呀

![微信截图_20230106201333](https://user-images.githubusercontent.com/22003930/211010783-195a2e5a-abb7-42a3-8624-4768f998fb84.png)

**Comment by banxian** [comment]
我的锅, 只传了代码, 二进制忘记上传到服务器了

**Comment by neomissing** [comment]
V12升级还是失败，无法升级成功，一直处于BootLoader模式，无法在退出了



***@***.***
 
发件人： banxian
发送时间： 2023-01-06 20:21
收件人： banxian/EDUReviver
抄送： neomissing; Author
主题： Re: [banxian/EDUReviver] SEGGER - J-Link V7.84a驱动JLINK EDU V10无法升级到V12 (Issue #4)
我的锅, 只传了代码, 二进制忘记上传到服务器了
―

**Comment by neomissing** [comment]
> 我的锅, 只传了代码, 二进制忘记上传到服务器了

![微信截图_20230106210323](https://user-images.githubusercontent.com/22003930/211017756-c6119acd-b3e8-4673-9c86-3889085a30ba.png)

**Comment by banxian** [comment]
从消息看对bootloader的补丁应该成功了
感觉是bootloader检测到新固件版本号比现有老会表现这样
先临时去掉了payload, 我给你个工具dump下1a008000开始的78000是不是更新了

**Comment by neomissing** [comment]
> 从消息看对bootloader的补丁应该成功了 感觉是bootloader检测到新固件版本号比现有老会表现这样 先临时去掉了payload, 我给你个工具dump下1a008000开始的78000是不是更新了

好的，麻烦给一下，多谢

**Comment by neomissing** [comment]
> 从消息看对bootloader的补丁应该成功了 感觉是bootloader检测到新固件版本号比现有老会表现这样 先临时去掉了payload, 我给你个工具dump下1a008000开始的78000是不是更新了

如果不能升级成功，希望给一个恢复工具，要不然就报废了

**Comment by banxian** [comment]
[JLinkDumper1_test.zip](https://github.com/banxian/EDUReviver/files/10360858/JLinkDumper1_test.zip)
先直接执行, dump出完整的bootloader和固件, 自己存好.
再执行JLinkDumper1.exe 0x1a008000 0x78000
带参数dump出来不包含bootloader的固件, 这个没有敏感信息可以打包发给我看看.
恢复工具我有一个也是通过刷机的, 得手动制作固件, 先搞定现在不能刷机原因再说.

**Comment by neomissing** [comment]
>

**Comment by neomissing** [comment]
[0x1a008000 0x78000固件.zip](https://github.com/banxian/EDUReviver/files/10361021/0x1a008000.0x78000.zip)

**Comment by banxian** [comment]
从你给的固件看固件部分刷进去了...
原因应该是, v12的bootloader重写了, 固件的签名范围变了. v10/11的bootloader认为新刷进去的固件签名错误. 所以应该用v11的固件刷回. 
执行jlinkupdater1 JLink_V11_neomissing
可以将bootloader补回v10
[JLinkUpdater1_neomissing.zip](https://github.com/banxian/EDUReviver/files/10362760/JLinkUpdater1_neomissing.zip)
建议恢复后使用edureviver -run swd打开pcb上swd, 然后就可以用另一个jlink的loadfile功能修砖了

**Comment by neomissing** [comment]
> 

多谢，已恢复

**Comment by neomissing** [comment]
完成
