### ISSUE TITLE
What is hardware version v12?

### ISSUE THREAD

**Issue by erazor-de** [banxian/EDUReviver#5]
The actual hardware versions of edu, base and such is v11. Is v12 an upcoming version or a different device?

**Comment by banxian** [comment]
seen on recent(7.84) jlink/jtrace driver package and release notes.
I guess v12 have same hardware to v11, and new bootloader with modified hash range.

**Comment by taoistding** [comment]
> seen on recent(7.84) jlink/jtrace driver package and release notes.
> I guess v12 have same hardware to v11, and new bootloader with modified hash range.

V12 firmware is started from Nov 14th 2022.  :)
Yes, same thinking from my side on new bootloader

**Comment by banxian** [comment]
confirmed. v12 pcba is same to v11.
