### ISSUE TITLE
V12变砖了估计无法修复了，问题描述下

### ISSUE THREAD

**Issue by ghost** [banxian/EDUReviver#6]
你好 Up主，我用的是JLINK-EDU，因为第一次用你的工具我首先用了-run to12 直接转换到了V12 玩玩的，此时我也没有用License注册啥的，然后我打开了JLinkCommander提示我对设备进行升级，因为我是正版嘛，然后就点了升级，然后卡死了，然后我就重新插拔了Jlink，强关了软件，然后我打开Configuration 软件，提示如下图
<img width="418" alt="image" src="https://user-images.githubusercontent.com/55439370/216663880-acca0d50-eaac-4200-b7c9-5ee26ec1ccfe.png">
然后我点击OK，如下图
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/55439370/216662937-877324b4-0350-42a1-868b-dbd18f9947d8.png">
然后我点击OK，我的Jlink再也不会在Configuration中出现了，还有什么办法修复吗，主要被我手欠转换成了V12，这东西我以为版本越高越好，此时执行blinky也没有用了，因为识别不到Jlink了。

请求UP主帮忙一下

**Comment by banxian** [comment]
我的锅, 这个问题是1月6号修复的, 原因是bootloader在v12更换了对固件的校验. 补一半后新刷的固件被当作错误固件. 我修复后也测试了, 但1月9号我觉得补丁有点大, "优化"了一下变回之前的大小了, 就开心的更新了, 由于未知原因, 新加的两行代码被llvm给"优化"丢了...
你这个还能进bootloader, 你告诉我一下序列号, 我给你刷机工具补上丢掉的部分...

**Comment by ghost** [comment]
> 
大神这么晚还没睡啊  我JLink后面贴的SN是260109770，  但是我JLINK没坏之前我进入Configuration复制的SN号为260109769,
现在我JLINK通过Commander都无法通过usb连接，只在任务管理器里面看到一个jlink， 还能刷机吗？

**Comment by banxian** [comment]
[JLinkUpdater1_kiraversace.zip](https://github.com/banxian/EDUReviver/files/10581527/JLinkUpdater1_kiraversace.zip)
先执行一下JLinkDumper1, 会备份出你现在的bootloader和签名, 自行保存好这个bin.
然后再执行JLinkUpdater1 JLink_V11_KiraVerSace
会强行刷入一个假固件, 然后再连接Commander升级.

**Comment by ghost** [comment]
果然成功了，作为一个小白我想请教下这个工具的作用是啥，转换成V10 V11  V12又如何？  破解添加证书又是啥意思？

**Comment by ghost** [comment]
即便我这么操作了，刚刚测试了下，在使用jlink的时候还是会跳出EDU的那个弹窗？

**Comment by banxian** [comment]
v12现在也就是尝鲜, 如果能买到原版的v12或许可以转换成真的v12.
v12 edu也还是edu, 这里不讨论抹除edu banner

**Comment by rayc345** [comment]
edu是不是最好不要刷成v12？
segger之前的上位机程序加了检测，部分SN被拉黑，还有根据SN检测，如果edu有jflash等功能也拉黑，担心日后有一天检测到v12 edu也会被拉黑

**Comment by banxian** [comment]
大壳子的edu不知道是否还继续出货? 我估计它可能都忘了非mini的edu了.
