### ISSUE TITLE
求救，EDU11板升级到V12无法使用，无法降级

### ISSUE THREAD

**Issue by ranli55** [banxian/EDUReviver#7]
半仙，您好，EDU V11版升级到V12后无法降级，使用降级命令后在commander页面插拔无降级反应，在闪灯命令界面提示
UID signature OK.
detect fake to12 Bootloader.
Your version number is not present in config cache! Analyst it now...

同时这个V12也没法使用，连接时提示芯片已加密需要解锁，空白芯片也如此，最后通讯错误超时退出 
* JLink Info: InitTarget() start
* JLink Info: InitTarget()
* JLink Info: Write protected device detected. This could cause problems during flash download.
Note: Unsecuring will trigger a mass erase of the internal flash.

* JLink Info: Executing default behavior previously saved in the registry.
* JLink Info: Device will be unsecured now.
* JLink Info: InitTarget() end - Took 60.0s
* JLink Info: Connect failed. Resetting via Reset pin and trying again.
* JLink Info: InitTarget() start
* JLink Info: InitTarget()
* JLink Info: Write protected device detected. This could cause problems during flash download.
Note: Unsecuring will trigger a mass erase of the internal flash.

* JLink Info: Executing default behavior previously saved in the registry.
* JLink Info: Device will be unsecured now.
* JLink Info: InitTarget() end - Took 60.0s
Error: Flash Erase failed  -  Target DLL has been cancelled
Flash Erase finished 19:53:12

**Comment by banxian** [comment]
关于无法降级问题: 发布时候只支持到了当时的7.82d版本驱动包, 下载该版本驱动包(可以免安装7zip解压), 运行jlinkconfig右键强制降级为该版本固件后便可以运行edureviver.
关于v12无法连接目标板: v12的compact版硬件我已拿到, 它PCBA跟v11一模一样, 按理edu也不会有PCB兼容问题. 你降级后再试试, 也不能擦的话可能是k22那种容易锁芯片的体质

**Comment by ranli55** [comment]
非常感谢您的回复，按照您的方法已经恢复正常了。无法连接目标板的问题是没有去除功能同时没有提示，恢复成V11后就提示the connected jlink is defective，最开始更新版本前也是有这个提示，升级后没有提示了就没注意，用工具去除之后就正常了。
