### ISSUE TITLE
EDU无法升降级

### ISSUE THREAD

**Issue by neomissing** [banxian/EDUReviver#8]
![QQ截图20240216145242](https://github.com/banxian/EDUReviver/assets/22003930/dfa5519f-6cad-4ef2-a3b1-37f12d69c4bd)

**Comment by banxian** [comment]
静态分析引擎不大适合新版本固件的编译器优化了.
放完假后我把获取栈快照的功能重构下吧.

**Comment by zbqxyz** [comment]
我的v11 base 也是这个提示信息，这个信息说明是盗版的么？

**Comment by banxian** [comment]
不说明, 忙, 现版本要重构, 等一位勇士发v12 bootloader再重写

**Comment by banxian** [comment]
已经换成从栈读回寄存器, 应该可以适配大部分新固件

**Comment by neomissing** [comment]
测试依然不行

**Comment by neomissing** [comment]
![Uploading Catch(10-10-20-14-01).jpg…]()

**Comment by neomissing** [comment]
![Catch(10-10-20-14-01)](https://github.com/user-attachments/assets/1be15bbd-25ec-4242-9d45-8bf215d1ea89)

**Comment by banxian** [comment]
我在本地测试过的, 在线验证hash的环境意外的被主机提供商搬家弄崩了. 回头移植成workers吧, 可惜win10以下访问有dns问题.
