### ISSUE TITLE
无法升级

### ISSUE THREAD

**Issue by zbqxyz** [banxian/EDUReviver#9]
E:\Download\EDUReviver_bin_b037>EDUReViver -run blinky
Firmware Version: J-Link V10 compiled Jan 30 2023 11:28:07, Hardware Version: 101000
sn: 820102413, checksum OK.
UID signature OK.
Select FINE interface: 0 -> 3

E:\Download\EDUReviver_bin_b037>EDUReViver -run swd
Firmware Version: J-Link V10 compiled Jan 30 2023 11:28:07, Hardware Version: 101000
sn: 820102413, checksum OK.
UID signature OK.
old CRP Level: NO CRP
Select FINE interface: 3 -> 3
new CRP Level: NO CRP

E:\Download\EDUReviver_bin_b037>EDUReViver -run revive
Firmware Version: J-Link V10 compiled Jan 30 2023 11:28:07, Hardware Version: 101000
sn: 820102413, checksum OK.
Features: GDB
UID signature OK.
Select FINE interface: 3 -> 3
Features: GDB

E:\Download\EDUReviver_bin_b037>EDUReViver -run to11
Firmware Version: J-Link V10 compiled Jan 30 2023 11:28:07, Hardware Version: 101000
sn: 820102413, checksum OK.
UID signature OK.
Detected clone.

使用的是v10.1 base compact ，设备时正版的，前面校验都能过，灯闪烁也对，但是转换时候提示时 clone ,这是啥情况？

**Comment by zbqxyz** [comment]
这个是用JLinkDumper1_test读出来的固件，

**Comment by zbqxyz** [comment]
这个是用JLinkDumper1_test读出来的固件，

**Comment by zbqxyz** [comment]
gu固件

**Comment by banxian** [comment]
是0.3.7发布的版本, 验证bootloader的代码把你的v10当作v12来验证了.
